[build-system]
requires = ["Setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
version = "0.1.0"
description = "click test"
readme = "README.md"
dependencies = [
    "click>=8.1.3", 
]
[project.scripts]
cli = "cli.main:cli"
